import type { Node } from '@xyflow/react'
import type { PersistedWorkspaceState, TerminalNodeData } from '../types'

export function toRuntimeNodes(workspace: PersistedWorkspaceState): Node<TerminalNodeData>[] {
  return workspace.nodes.map(node => ({
    id: node.id,
    type: node.kind === 'task' ? 'taskNode' : 'terminalNode',
    position: node.position,
    data: {
      sessionId: '',
      title: node.title,
      width: node.width,
      height: node.height,
      kind: node.kind,
      status: node.status,
      startedAt: node.startedAt,
      endedAt: node.endedAt,
      exitCode: node.exitCode,
      lastError: node.lastError,
      scrollback: node.scrollback,
      agent: node.agent,
      task:
        node.kind === 'task'
          ? (node.task ?? {
              requirement: '',
              status: 'todo',
              priority: 'medium',
              tags: [],
              linkedAgentNodeId: null,
              lastRunAt: null,
              autoGeneratedTitle: false,
              createdAt: null,
              updatedAt: null,
            })
          : null,
    },
    draggable: true,
    selectable: true,
  }))
}
