blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/DeadWaveWave/opencove/discussions
    about: Please ask and answer questions here.
  - name: 🔒 Report a Security Vulnerability
    url: https://github.com/DeadWaveWave/opencove/security/advisories/new
    about: Please refrain from opening public issues for security vulnerabilities.
