import type { Node } from '@xyflow/react'
import type {
  NodeFrame,
  TerminalNodeData,
  SpaceArchiveGitSnapshot,
  SpaceArchiveRecord,
  WorkspaceSpaceState,
} from '../types'

const MAX_SPACE_ARCHIVE_RECORDS = 50

function normalizeOptionalString(value: unknown): string | null {
  if (typeof value !== 'string') {
    return null
  }

  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : null
}

function toArchiveNodeFrame(node: Node<TerminalNodeData>): NodeFrame {
  return {
    position: {
      x: node.position.x,
      y: node.position.y,
    },
    size: {
      width: node.data.width,
      height: node.data.height,
    },
  }
}

export function buildSpaceArchiveRecord({
  space,
  nodes,
  git = null,
  archivedAt = new Date().toISOString(),
  recordId = crypto.randomUUID(),
}: {
  space: WorkspaceSpaceState
  nodes: Node<TerminalNodeData>[]
  git?: SpaceArchiveGitSnapshot | null
  archivedAt?: string
  recordId?: string
}): SpaceArchiveRecord {
  const nodeById = new Map(nodes.map(node => [node.id, node]))
  const snapshots = space.nodeIds
    .map(nodeId => nodeById.get(nodeId) ?? null)
    .filter((node): node is Node<TerminalNodeData> => node !== null)
    .map(node => {
      const frame = toArchiveNodeFrame(node)
      const labelColorOverride = node.data.labelColorOverride ?? null

      switch (node.data.kind) {
        case 'terminal':
          return {
            kind: 'terminal' as const,
            id: node.id,
            title: node.data.title,
            frame,
            labelColorOverride,
            runtimeKind: node.data.runtimeKind ?? null,
            executionDirectory: normalizeOptionalString(node.data.executionDirectory),
            expectedDirectory: normalizeOptionalString(node.data.expectedDirectory),
            startedAt: node.data.startedAt,
            endedAt: node.data.endedAt,
            exitCode: node.data.exitCode,
            lastError: node.data.lastError,
          }
        case 'agent':
          return {
            kind: 'agent' as const,
            id: node.id,
            title: node.data.title,
            frame,
            labelColorOverride,
            status: node.data.status,
            provider: node.data.agent?.provider ?? null,
            prompt: node.data.agent?.prompt ?? '',
            model: node.data.agent?.model ?? null,
            effectiveModel: node.data.agent?.effectiveModel ?? null,
            launchMode: node.data.agent?.launchMode ?? null,
            resumeSessionId: node.data.agent?.resumeSessionId ?? null,
            ...(node.data.agent?.resumeSessionIdVerified === true
              ? { resumeSessionIdVerified: true as const }
              : {}),
            executionDirectory:
              normalizeOptionalString(node.data.agent?.executionDirectory) ?? null,
            expectedDirectory: normalizeOptionalString(node.data.agent?.expectedDirectory) ?? null,
            directoryMode: node.data.agent?.directoryMode ?? null,
            customDirectory: normalizeOptionalString(node.data.agent?.customDirectory) ?? null,
            shouldCreateDirectory: node.data.agent?.shouldCreateDirectory === true,
            taskId: normalizeOptionalString(node.data.agent?.taskId) ?? null,
            startedAt: node.data.startedAt,
            endedAt: node.data.endedAt,
            exitCode: node.data.exitCode,
            lastError: node.data.lastError,
          }
        case 'task':
          return {
            kind: 'task' as const,
            id: node.id,
            title: node.data.title,
            frame,
            labelColorOverride,
            requirement: node.data.task?.requirement ?? '',
            status: node.data.task?.status ?? 'todo',
            priority: node.data.task?.priority ?? 'medium',
            tags: node.data.task?.tags ?? [],
            linkedAgentNodeId: node.data.task?.linkedAgentNodeId ?? null,
            lastRunAt: node.data.task?.lastRunAt ?? null,
            autoGeneratedTitle: node.data.task?.autoGeneratedTitle === true,
            createdAt: node.data.task?.createdAt ?? null,
            updatedAt: node.data.task?.updatedAt ?? null,
          }
        case 'note':
          return {
            kind: 'note' as const,
            id: node.id,
            title: node.data.title,
            frame,
            labelColorOverride,
            text: node.data.note?.text ?? '',
          }
        default:
          return null
      }
    })
    .filter(item => item !== null)

  return {
    id: recordId,
    archivedAt,
    git,
    space: {
      id: space.id,
      name: space.name,
      directoryPath: space.directoryPath,
      labelColor: space.labelColor,
      rect: space.rect,
    },
    nodes: snapshots,
  }
}

export function appendSpaceArchiveRecord(
  previous: SpaceArchiveRecord[],
  next: SpaceArchiveRecord,
): SpaceArchiveRecord[] {
  const normalized = Array.isArray(previous) ? previous : []
  return [next, ...normalized].slice(0, MAX_SPACE_ARCHIVE_RECORDS)
}
